blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/momorph/cli#readme
    about: Check out the documentation before opening an issue
  - name: Discussions
    url: https://github.com/momorph/cli/discussions
    about: Ask questions and discuss ideas
